version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://Pablo:contraseniaPablo@90.106.182.13:25015/?authMechanism=DEFAULT
      - HOST = "90.106.182.13"
      - PORT = 3304
      - USER = "administrador"
      - PASSWORD = "password"
      - SALT = "Lur9vFWtHdexGGUsYbe7Tni0zjvSVvC0gt3Tm4RebKM="