version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://Pablo:contraseniaPablo@90.164.253.234:25015/?authMechanism=DEFAULT
      - HOST = "90.164.253.234"
      - PORT = 3304
      - USER = "administrador"
      - PASSWORD = "password"